import { createAction } from 'redux-actions'

export const ADD_CARD_TO_BASKET_REQUEST = createAction('ADD_CARD_TO_BASKET_REQUEST');
export const ADD_CARD_TO_BASKET_SUCCESS = createAction('ADD_CARD_TO_BASKET_SUCCESS')
export const ADD_CARD_TO_BASKET_FAIL = createAction('ADD_CARD_TO_BASKET_FAIL')

export const GET_BASKET_PRODUCTS_REQUEST = createAction('GET_BASKET_PRODUCTS_REQUEST');
export const GET_BASKET_PRODUCTS_SUCCESS = createAction('GET_BASKET_PRODUCTS_SUCCESS')
export const GET_BASKET_PRODUCTS_FAIL = createAction('GET_BASKET_PRODUCTS_FAIL')

export const CLEAN_BASKET_PRODUCTS = createAction('CLEAN_BASKET_PRODUCTS')

export const CHANGE_QUANTITY_OF_PRODUCT_REQUEST = createAction('CHANGE_QUANTITY_OF_PRODUCT_REQUEST');
export const CHANGE_QUANTITY_OF_PRODUCT_SUCCESS = createAction('CHANGE_QUANTITY_OF_PRODUCT_SUCCESS')
export const CHANGE_QUANTITY_OF_PRODUCT_FAIL = createAction('CHANGE_QUANTITY_OF_PRODUCT_FAIL')
